# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 13:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import timezone_field.fields
import trapper.apps.common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_code', models.CharField(max_length=50)),
                ('deployment_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('correct_setup', models.BooleanField(default=True)),
                ('correct_tstamp', models.BooleanField(default=True)),
                ('view_quality', models.CharField(blank=True, choices=[(b'Exclude', b'Exclude'), (b'Acceptable', b'Acceptable'), (b'Good', b'Good'), (b'Perfect', b'Perfect')], default=b'Good', max_length=255, null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('comments', trapper.apps.common.fields.SafeTextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['deployment_id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('timezone', timezone_field.fields.TimeZoneField(default=b'Europe/Warsaw')),
                ('country', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('state', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('county', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('city', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_locations', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_locations', to=settings.AUTH_USER_MODEL)),
                ('research_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.ResearchProject')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='geomap.Location'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_deployments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deployment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_deployments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deployment',
            name='research_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.ResearchProject'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
