# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('href', models.SlugField(blank=True, editable=False, null=True, verbose_name='Slug')),
                ('url', models.CharField(blank=True, max_length=50, null=True, verbose_name='External URL')),
                ('css_class', models.CharField(blank=True, help_text='http://fortawesome.github.io/Font-Awesome/icons/', max_length=20, null=True, verbose_name='Fontawesome class')),
            ],
        ),
    ]
