# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('family', models.CharField(blank=True, max_length=100)),
                ('genus', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['english_name'],
            },
        ),
    ]
